name: "HUE Action"
description: "Change the HUE lights color based on the CI build state"
inputs:
  hueWebhook:
    description: "The HUE Action webhook (from hueaction.dev)"
    required: true
  hueLightId:
    description: "The HUE light ID"
    required: false
    default: "1"
outputs:
  lightStatus:
    description: "The light status"
runs:
  using: "node12"
  main: "index.js"
